
name: check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Style-check ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only lint on the min and max supported Python versions.
        # It's extremely unlikely that there's a lint issue on any version in between
        # that doesn't show up on the min or max versions.
        #
        # GitHub rate-limits how many jobs can be running at any one time.
        # Starting new jobs is also relatively slow,
        # so linting on fewer versions makes CI faster.
        python-version:
          - "3.8"
          - "3.11"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev,all]

    - name: check-sort-import
      run: |
        make check-sort-imports

    - name: check-black-format
      run: |
        make check-format

    - name: check-mypy
      run: |
        make mypy
