name: deploy-release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build_release:
    if: |
        ${{ github.event.pull_request.merged == true }}
        && ${{ contains(github.event.pull_request.labels.*.name, 'release') }}
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel

      - name: check-version
        run: |
          echo "VERSION=$(python setup.py --version)" >> $GITHUB_OUTPUT

      - name: create python package
        run: python setup.py sdist bdist_wheel

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          generateReleaseNotes: true
          tag: v${{ steps.check-version.outputs.VERSION }}
          commit: main

      - name: deploy
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI }}
          repository_url: https://test.pypi.org/legacy/