name: Test Suite

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  test:
    name: Python ${{ matrix.python-version }} - ${{ matrix.connection }} [redis-stack ${{matrix.redis-stack-version}}]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11, 'pypy-3.7', 'pypy-3.8', 'pypy-3.9']
        connection: ['hiredis', 'plain']
        redis-stack-version: ['latest', 'edge', '6.2.6-v9']

    services:
      redis:
        image: redis/redis-stack-server:${{matrix.redis-stack-version}}
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev,all]

    - name: Install hiredis if needed
      if: matrix.connection == 'hiredis'
      run: |
        pip install hiredis

    - name: Start Redis
      run: |
        REDIS_URL=redis://localhost:6379
        echo REDIS_URL=$REDIS_URL >> $GITHUB_ENV

    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
      run: |
        make test-cov
    - name: Run notebooks
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
      run: |
        cd docs/ && treon -v --exclude="./examples/openai_qna.ipynb"
    - name: Publish coverage results
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true